Add tests via pytest, asynctest
NERSC/sshapiauthenticator pull request #5
Opened 2019-05-23 20:51 UTC by tslaton

Currently these tests do not necessarily represent server behavior faithfully, but they do achieve 100% coverage of `sshapiauthenticator/auth.py`. 

They also demonstrate one straightforward means of mocking out asynchronous network code.

There may be a cleaner method of generating a valid ssh key without calling `ssh-keygen` via `subprocess`. Although the method currently used will produce temporary files on the user's system, it also removes them.

2019-05-28 21:55 UTC, scanon requested changes
This is looking good.  I think add a few more tests and some logging and it is good for a first cut.

2019-05-28 21:55 UTC, scanon commented on tests/test_authenticator.py
> +    assert resp == 'tester'
Maybe add some tests to confirm that the ssh files were created.

2019-05-28 21:55 UTC, scanon commented on tests/test_authenticator.py
> +    assert resp == 'tester'
Do this for all the successful tests.

2019-05-28 21:55 UTC, scanon commented on tests/test_authenticator.py
> +    assert resp is None
If we add logging, then you could mock the log call and confirm that some log message is being generated.

2019-05-29 22:24 UTC, tslaton commented
I added checks for the file creation and some log messages. I'm still not 100% sure I'm logging the best messages.

I added a bit about the response error code and human readable reason to the logs in the case where all of that is defined.

2019-05-30 21:45 UTC, scanon approved these changes
This all looks good.

2019-05-30 21:47 UTC, merged